### ISSUE TITLE
May 2019 - Scheduled content update

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-Big-Compute#18]
@ZoinerTejada @joelhulen @kylebunting
Solliance team -
This workshop is scheduled for an update in March. Please update this issue with suggested content changes. Once done, we'll assign to our SME team for review and additional feedback.

**Comment by kylebunting** [comment]
Here are my suggested updates for this MCW:

- Move deployment of Jump Box into Before the HOL.
- Add clarification around steps to create the batch job files (pool.json and job.json), to avoid potential for errors when copying and pasting file content.

**Comment by DawnmarieDesJardins** [comment]
March update was placed on hold - moving to May.  
@kylebunting 
Kyle, please review your original update suggestions.  Anything you'd like to add or remove?

**Development Schedule**
Update issue re-opened:  4/1/19 
Update suggestions due:  4/8/19
SME suggestions review:  4/9/19 – 4/12/19
Draft due:  5/8/19
SME review:  5/9/19 – 5/20/19
Final due:  5/23/19
Publish date:  5/28/19

**Comment by joelhulen** [comment]
I am good with those suggestions. There may be new changes to the portal UI, services, and features that will need to be updated as well since the last time this MCW has been touched.

**Comment by hirtanak** [comment]
Hi All, I suggest to cover more other industrial scenarios.
For example, Automotive, AeroSpace, Manufacturing, Power & Process industries require CAE, MD.
We have already some handson scenarios as below.
https://docs.microsoft.com/en-us/azure/cyclecloud/quickstart-install-cyclecloud
https://docs.microsoft.com/en-us/azure/cyclecloud/tutorials/modify-cluster-template
https://docs.microsoft.com/en-us/azure/cyclecloud/tutorials/deploy-custom-application

CAE: https://en.wikipedia.org/wiki/Computer-aided_engineering
MD:  https://en.wikipedia.org/wiki/Molecular_dynamics

**Comment by joelhulen** [comment]
@hirtanak Thanks for your suggestion. However, I am not sure exactly what you are asking as it pertains to this update. Are you wanting to change the entire customer scenario for the whiteboard design session to one of the ones you mentioned, or are you suggesting that we add links to the additional scenarios you mention that cover other industries? The way the whiteboard design sessions work is that attendees are presented with a customer scenario that has a number of challenges related to the primary topic (in this case, Big Compute). These challenges oftentimes cover a cross-section of technical areas but there is a story being told as well to represent a real customer situation. The attendees are then challenged to address the technical and business requirements, and to address each of the customer's objections. The hands-on lab continues with the customer scenario by allowing attendees to implement the preferred solution themselves.

Given this flow, you can understand the difficulty in adding additional scenarios. Because of this, perhaps it's best to link to these other scenarios for further reading and labs.

**Comment by DawnmarieDesJardins** [comment]
This update was placed on hold.  Closing this issue and opening a new one with consolidated notes to keep the update clean.
